"""
Unit Tests for Frontend JavaScript Tracker Contract (TASK-3.3).
Validates:
1. Syntax validity via Node.js compiler.
2. Binary footprint and gzip compression (< 3.5 KB budget).
3. Payload JSON contract compatibility with RawTrafficEventDTO.
4. Edge cases (session_id generation, UTM sanitization, incognito fallback).
"""
import os
import gzip
import subprocess
import pytest
from src.models.events import RawTrafficEventDTO

TRACKER_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "web",
    "public",
    "swipies-tracker.js"
)


def test_tracker_file_exists_and_node_syntax():
    """Verify swipies-tracker.js exists and has 0 syntax errors according to Node.js."""
    assert os.path.exists(TRACKER_PATH), f"Tracker file missing at {TRACKER_PATH}"
    
    res = subprocess.run(
        ["node", "-c", TRACKER_PATH],
        capture_output=True,
        text=True
    )
    assert res.returncode == 0, f"Node syntax error in tracker: {res.stderr}"


def test_tracker_gzip_size_budget():
    """Verify that gzipped bundle size is strictly below the 3.5 KB threshold."""
    with open(TRACKER_PATH, "rb") as f:
        raw_bytes = f.read()

    compressed = gzip.compress(raw_bytes)
    size_kb = len(compressed) / 1024.0

    assert len(compressed) <= 3584, f"Tracker gzipped size ({size_kb:.2f} KB) exceeds 3.5 KB budget!"


def test_tracker_payload_matches_pydantic_dto():
    """Verify sample payload generated by tracker strictly validates against RawTrafficEventDTO."""
    sample_js_payload = {
        "session_id": "swp_m8x2k9_7a8b9c1234ef",
        "page_path": "/pricing",
        "time_on_page_sec": 35,
        "utm_source": "meta",
        "utm_medium": "story_cpc",
        "utm_campaign": "spring_b2b_uz",
        "utm_content": "creative_carousel_01",
        "utm_term": "invoice_factoring",
        "referrer": "https://m.facebook.com/",
        "event_type": "pageview"
    }

    # Combined with server-side anonymized IP hash
    full_event = RawTrafficEventDTO(
        ip_hash="a" * 64,
        country="UZ",
        city="Tashkent",
        **sample_js_payload
    )

    assert full_event.session_id == sample_js_payload["session_id"]
    assert full_event.page_path == "/pricing"
    assert full_event.time_on_page_sec == 35
    assert full_event.utm_source == "meta"
    assert full_event.utm_campaign == "spring_b2b_uz"


def test_tracker_mock_runtime_in_node():
    """Executes a micro Node test harness verifying DOM and Storage fallback behaviors."""
    node_script = """
    const fs = require('fs');
    const trackerCode = fs.readFileSync(process.argv[1], 'utf8');

    // Minimal browser mock
    let cookies = '';
    const mockStorage = {};

    global.window = {
        sessionStorage: {
            getItem: (k) => mockStorage[k] || null,
            setItem: (k, v) => { mockStorage[k] = v; }
        },
        location: {
            search: '?utm_source=meta&utm_campaign=fintech_promo&fbclid=IwAR123',
            pathname: '/checkout'
        },
        addEventListener: () => {}
    };
    global.document = {
        get cookie() { return cookies; },
        set cookie(v) { cookies = v; },
        addEventListener: () => {},
        visibilityState: 'visible',
        referrer: 'https://l.instagram.com/'
    };
    global.navigator = { sendBeacon: () => true };

    // Execute tracker
    eval(trackerCode);

    // Assert tracker loaded and exposed API
    if (!global.window.__SWIPIES_TRACKER__) {
        console.error("Tracker API not mounted to window");
        process.exit(1);
    }

    const sess = global.window.__SWIPIES_TRACKER__.getSessionId();
    if (!sess || !sess.startsWith('swp_')) {
        console.error("Invalid session ID generated:", sess);
        process.exit(2);
    }

    const utm = global.window.__SWIPIES_TRACKER__.getUtm();
    if (utm.utm_source !== 'meta' || utm.utm_campaign !== 'fintech_promo') {
        console.error("UTM parsing failed:", utm);
        process.exit(3);
    }

    console.log("SUCCESS");
    process.exit(0);
    """

    res = subprocess.run(
        ["node", "-e", node_script, TRACKER_PATH],
        capture_output=True,
        text=True
    )
    assert res.returncode == 0, f"Node runtime test failed:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}"
    assert "SUCCESS" in res.stdout
